name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir -p dist

      - name: Generate Snake SVG with dark theme
        uses: DaSchTour/snk@custom-color-support
        with:
          github_user_name: DaRKxLoRd18
          outputs: dist/github-contribution-grid-snake.svg
          snake_color: '#00ffe0' # neon cyan
          background: '#0d1117'  # GitHub dark background
          color_dots: '#161b22,#1f2933,#263544,#2f3e50,#39d353' # darkest to active

      - name: Show output files
        run: ls -R dist

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
